#### 本部分主要用于构建FF3因子数据
参考：https://blog.csdn.net/weixin_47515729/article/details/123283505?ops_request_misc=elastic_search_misc&request_id=42a760f106e99a8214a21a60b9720cf3&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-123283505-null-null.142^v102^pc_search_result_base2&utm_term=ff3因子&spm=1018.2226.3001.4187

In [16]:
#导入必要的库
import pandas as pd
import tushare as ts
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt 
from tqdm import tqdm, trange  #进度条可视化
import datetime
import time
from config.config import *

In [17]:
pro = ts.pro_api()  
#定义函数获取每日指标
def get_daily_basic(stock_codes,start_date,end_date):  #参数类型：list,string,string
    df = pro.daily_basic(ts_code=[''], start_date='', end_date='')  #生成一个空的dataframe
    pbar = tqdm(stock_codes)
    for codes in pbar:
        st = time.time()
        pbar.set_description('Processing '+codes)
        df1 = pro.daily_basic(ts_code=codes, start_date=start_date, end_date=end_date)
        df = pd.concat([df,df1],ignore_index=True) 
        et = time.time()
        t = et-st
        if t<0.3:
            time.sleep(0.3-t)
    return df

In [ ]:
# #获取所有上市公司股票列表
# stocks_listL =pro.stock_basic(exchange='', list_status='L', fields='ts_code,symbol,name,area,industry,list_date,delist_date')
# stock_codes = stocks_listL['ts_code'].tolist()
# #获取所有上市公司的每日指标
# data = get_daily_basic(stock_codes,'20160101','20260327')

In [58]:
# data.to_csv("ff3/daily_basic_2016_to_2026.csv")  #数据量过多，存到本地方便调用
data = pd.read_csv("ff3/daily_basic_2016_to_2026.csv")

In [22]:
index_daily = pro.index_daily(ts_code='399300.SZ', start_date='20160101', end_date='20260327').sort_values('trade_date').reset_index()

In [75]:
data

,Unnamed: 0,ts_code,trade_date,close,turnover_rate,turnover_rate_f,volume_ratio,pe,pe_ttm,pb,ps,ps_ttm,dv_ratio,dv_ttm,total_share,float_share,free_share,total_mv,circ_mv
0,0,000001.SZ,20260327,11.02,0.4556,1.0834,0.79,5.0161,5.0161,0.4739,1.6270,1.6270,5.4266,5.4266,1.940592e+06,1.940560e+06,816048.1215,2.138532e+07,2.138497e+07
1,1,000001.SZ,20260326,10.94,0.4265,1.0142,0.77,4.9797,4.9797,0.4705,1.6152,1.6152,5.4663,5.4663,1.940592e+06,1.940560e+06,816048.1215,2.123007e+07,2.122973e+07
2,2,000001.SZ,20260325,10.94,0.3838,0.9127,0.68,4.9797,4.9797,0.4705,1.6152,1.6152,5.4663,5.4663,1.940592e+06,1.940560e+06,816048.1215,2.123007e+07,2.122973e+07
3,3,000001.SZ,20260324,10.88,0.8360,1.9879,1.65,4.9524,4.9524,0.4679,1.6063,1.6063,5.4964,5.4964,1.940592e+06,1.940560e+06,816048.1215,2.111364e+07,2.111329e+07
4,4,000001.SZ,20260323,10.45,0.8142,1.9363,1.95,4.7567,4.7567,0.4494,1.5428,1.5428,5.7226,5.7226,1.940592e+06,1.940560e+06,816048.1215,2.027918e+07,2.027885e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10081046,10081046,301682.SZ,20260325,128.65,76.5912,76.5912,NaN,49.0626,49.0626,3.2152,5.9761,5.9761,NaN,NaN,1.215494e+04,2.568682e+03,2568.6821,1.563732e+06,3.304610e+05
10081047,10081047,688781.SH,20260327,39.30,29.3957,29.3957,NaN,NaN,NaN,9.5975,76.6021,76.6021,NaN,NaN,1.000000e+05,4.083510e+03,4083.5097,3.930000e+06,1.604819e+05
10081048,10081048,688781.SH,20260326,40.79,53.8365,53.8365,NaN,NaN,NaN,9.9614,79.5063,79.5063,NaN,NaN,1.000000e+05,4.083510e+03,4083.5097,4.079000e+06,1.665664e+05
10081049,10081049,688781.SH,20260325,46.00,77.5804,77.5804,NaN,NaN,NaN,11.2337,89.6614,89.6614,NaN,NaN,1.000000e+05,4.083510e+03,4083.5097,4.600000e+06,1.878414e+05
10081050,10081050,920069.BJ,20260327,43.48,65.5272,65.5272,NaN,25.6272,25.6272,2.9988,6.0197,6.0197,NaN,NaN,5.291400e+03,1.477774e+03,1477.7735,2.300701e+05,6.425359e+04

In [60]:
data.fillna(method='ffill', axis=0, inplace=False)

/var/folders/ss/hq0_l7mj2f35ct8zlh27s1p80000gn/T/ipykernel_61384/3780134201.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', axis=0, inplace=False)

,Unnamed: 0,ts_code,trade_date,close,turnover_rate,turnover_rate_f,volume_ratio,pe,pe_ttm,pb,ps,ps_ttm,dv_ratio,dv_ttm,total_share,float_share,free_share,total_mv,circ_mv
0,0,000001.SZ,20260327,11.02,0.4556,1.0834,0.79,5.0161,5.0161,0.4739,1.6270,1.6270,5.4266,5.4266,1.940592e+06,1.940560e+06,816048.1215,2.138532e+07,2.138497e+07
1,1,000001.SZ,20260326,10.94,0.4265,1.0142,0.77,4.9797,4.9797,0.4705,1.6152,1.6152,5.4663,5.4663,1.940592e+06,1.940560e+06,816048.1215,2.123007e+07,2.122973e+07
2,2,000001.SZ,20260325,10.94,0.3838,0.9127,0.68,4.9797,4.9797,0.4705,1.6152,1.6152,5.4663,5.4663,1.940592e+06,1.940560e+06,816048.1215,2.123007e+07,2.122973e+07
3,3,000001.SZ,20260324,10.88,0.8360,1.9879,1.65,4.9524,4.9524,0.4679,1.6063,1.6063,5.4964,5.4964,1.940592e+06,1.940560e+06,816048.1215,2.111364e+07,2.111329e+07
4,4,000001.SZ,20260323,10.45,0.8142,1.9363,1.95,4.7567,4.7567,0.4494,1.5428,1.5428,5.7226,5.7226,1.940592e+06,1.940560e+06,816048.1215,2.027918e+07,2.027885e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10081046,10081046,301682.SZ,20260325,128.65,76.5912,76.5912,0.42,49.0626,49.0626,3.2152,5.9761,5.9761,1.3051,1.2723,1.215494e+04,2.568682e+03,2568.6821,1.563732e+06,3.304610e+05
10081047,10081047,688781.SH,20260327,39.30,29.3957,29.3957,0.42,49.0626,49.0626,9.5975,76.6021,76.6021,1.3051,1.2723,1.000000e+05,4.083510e+03,4083.5097,3.930000e+06,1.604819e+05
10081048,10081048,688781.SH,20260326,40.79,53.8365,53.8365,0.42,49.0626,49.0626,9.9614,79.5063,79.5063,1.3051,1.2723,1.000000e+05,4.083510e+03,4083.5097,4.079000e+06,1.665664e+05
10081049,10081049,688781.SH,20260325,46.00,77.5804,77.5804,0.42,49.0626,49.0626,11.2337,89.6614,89.6614,1.3051,1.2723,1.000000e+05,4.083510e+03,4083.5097,4.600000e+06,1.878414e+05
10081050,10081050,920069.BJ,20260327,43.48,65.5272,65.5272,0.42,25.6272,25.6272,2.9988,6.0197,6.0197,1.3051,1.2723,5.291400e+03,1.477774e+03,1477.7735,2.300701e+05,6.425359e+04

In [25]:
#（按市值分为Small与Big两组，分别为50%；按照账面市值比BM分为30%，40%，30%的H,M,L组）
def mark_FF_group(df):
    #输入的dataframe为每年五月初的数据（我国的上市公司年报一般在4月底公布）
    #1.标记H,M,L;
    df['group_BM'] = 'M'  #初始化分组为'M'
    df.loc[df['BM']>=df['BM'].quantile(0.7),'group_BM'] = 'H'  #前30%划分为'H'
    df.loc[df['BM']<df['BM'].quantile(0.3),'group_BM'] = 'L'  #后30%划分为'L'
    
    #2.标记SIZE;
    df['group_SIZE'] = 'S'  #初始化分组为'S'
    df.loc[df['mkt']>=df['mkt'].quantile(0.5),'group_SIZE'] = 'B'  #前50%划分为'B'
    
    #3.分别划分为 B/H, B/M, B/L, S/H, S/M, S/L 六个组合
    df['portflio_mark'] =df['group_SIZE'] +'/'+df['group_BM']
    
    return df

In [ ]:
data_16_1 = pd.DataFrame(data[data['trade_date']==20160303], columns=['trade_date','ts_code','close','pb','total_mv']).rename(columns={'total_mv':'mkt'}).reset_index(drop=True)
data_16_1['BM'] = data_16_1['pb'].apply(lambda x : 1/x)
mark_FF_group(data_16_1)

data_17_1 = pd.DataFrame(data[data['trade_date']==20170301], columns=['trade_date','ts_code','close','pb','total_mv']).rename(columns={'total_mv':'mkt'}).reset_index(drop=True)
data_17_1['BM'] = data_17_1['pb'].apply(lambda x : 1/x)
mark_FF_group(data_17_1)

data_18_1 = pd.DataFrame(data[data['trade_date']==20180301], columns=['trade_date','ts_code','close','pb','total_mv']).rename(columns={'total_mv':'mkt'}).reset_index(drop=True)
data_18_1['BM'] = data_18_1['pb'].apply(lambda x : 1/x)
mark_FF_group(data_18_1)

data_19_1 = pd.DataFrame(data[data['trade_date']==20190301], columns=['trade_date','ts_code','close','pb','total_mv']).rename(columns={'total_mv':'mkt'}).reset_index(drop=True)
data_19_1['BM'] = data_19_1['pb'].apply(lambda x : 1/x)
mark_FF_group(data_19_1)

data_20_1 = pd.DataFrame(data[data['trade_date']==20200303], columns=['trade_date','ts_code','close','pb','total_mv']).rename(columns={'total_mv':'mkt'}).reset_index(drop=True)
data_20_1['BM'] = data_20_1['pb'].apply(lambda x : 1/x)
mark_FF_group(data_20_1)

data_21_1 = pd.DataFrame(data[data['trade_date']==20210303], columns=['trade_date','ts_code','close','pb','total_mv']).rename(columns={'total_mv':'mkt'}).reset_index(drop=True)
data_21_1['BM'] = data_21_1['pb'].apply(lambda x : 1/x)
mark_FF_group(data_21_1)

data_22_1 = pd.DataFrame(data[data['trade_date']==20220303], columns=['trade_date','ts_code','close','pb','total_mv']).rename(columns={'total_mv':'mkt'}).reset_index(drop=True)
data_22_1['BM'] = data_22_1['pb'].apply(lambda x : 1/x)
mark_FF_group(data_22_1)

data_23_1 = pd.DataFrame(data[data['trade_date']==20230303], columns=['trade_date','ts_code','close','pb','total_mv']).rename(columns={'total_mv':'mkt'}).reset_index(drop=True)
data_23_1['BM'] = data_23_1['pb'].apply(lambda x : 1/x)
mark_FF_group(data_23_1)

data_24_1 = pd.DataFrame(data[data['trade_date']==20240301], columns=['trade_date','ts_code','close','pb','total_mv']).rename(columns={'total_mv':'mkt'}).reset_index(drop=True)
data_24_1['BM'] = data_24_1['pb'].apply(lambda x : 1/x)
mark_FF_group(data_24_1)

data_25_1 = pd.DataFrame(data[data['trade_date']==20250303], columns=['trade_date','ts_code','close','pb','total_mv']).rename(columns={'total_mv':'mkt'}).reset_index(drop=True)
data_25_1['BM'] = data_25_1['pb'].apply(lambda x : 1/x)
mark_FF_group(data_25_1)

data_26_1 = pd.DataFrame(data[data['trade_date']==20260303], columns=['trade_date','ts_code','close','pb','total_mv']).rename(columns={'total_mv':'mkt'}).reset_index(drop=True)
data_26_1['BM'] = data_26_1['pb'].apply(lambda x : 1/x)
mark_FF_group(data_26_1)

,trade_date,ts_code,close,pb,mkt,BM,group_BM,group_SIZE,portflio_mark
0,20170301,000001.SZ,9.49,0.9140,1.629472e+07,1.094092,H,B,B/H
1,20170301,000002.SZ,20.50,2.2539,2.263026e+07,0.443675,H,B,B/H
2,20170301,000004.SZ,39.45,34.4297,3.312880e+05,0.029045,L,S,S/L
3,20170301,000006.SZ,8.77,2.7248,1.183946e+06,0.366999,H,B,B/H
4,20170301,000008.SZ,8.73,4.0558,2.452325e+06,0.246560,M,B,B/M
...,...,...,...,...,...,...,...,...,...
2707,20170301,001979.SZ,17.45,2.7438,1.379264e+07,0.364458,H,B,B/H
2708,20170301,002827.SZ,30.48,7.4930,5.608320e+05,0.133458,L,S,S/L
2709,20170301,002826.SZ,32.50,11.0874,6.165900e+05,0.090192,L,S,S/L
2710,20170301,603429.SH,68.63,11.3486,4.666840e+05,0.088117,L,S,S/L
2711,20170301,300607.SZ,76.31,9.1100,5.530020e+05,0.109769,L,S,S/L

In [ ]:
# #合并两年数据并标记
# data_5 = pd.concat([data_16_1,data_17_1],ignore_index=True).reset_index(drop=True)
# data_5['portflio_date'] = data_5['trade_date'].apply(lambda x:x//100)
# data_5

,trade_date,ts_code,close,pb,mkt,BM,group_BM,group_SIZE,portflio_mark,portflio_date
0,20160303,000001.SZ,10.11,0.9206,1.446607e+07,1.086248,H,B,B/H,201603
1,20160303,000004.SZ,29.86,30.3096,2.507544e+05,0.032993,L,S,S/L,201603
2,20160303,000006.SZ,9.38,2.8763,1.266295e+06,0.347669,M,B,B/M,201603
3,20160303,000008.SZ,8.33,4.4613,2.223143e+06,0.224150,M,B,B/M,201603
4,20160303,000009.SZ,12.25,4.3639,1.950332e+06,0.229153,M,B,B/M,201603
...,...,...,...,...,...,...,...,...,...,...
5071,20170301,001979.SZ,17.45,2.7438,1.379264e+07,0.364458,H,B,B/H,201703
5072,20170301,002827.SZ,30.48,7.4930,5.608320e+05,0.133458,L,S,S/L,201703
5073,20170301,002826.SZ,32.50,11.0874,6.165900e+05,0.090192,L,S,S/L,201703
5074,20170301,603429.SH,68.63,11.3486,4.666840e+05,0.088117,L,S,S/L,201703
5075,20170301,300607.SZ,76.31,9.1100,5.530020e+05,0.109769,L,S,S/L,201703

In [130]:
#合并两年数据并标记
df_list = [globals()[f"data_{i}_1"] for i in range(16, 27)]
data_10 = pd.concat(df_list, ignore_index=True).reset_index(drop=True)
data_10['portflio_date'] = data_10['trade_date'].apply(lambda x:x//100)
data_10

,trade_date,ts_code,close,pb,mkt,BM,group_BM,group_SIZE,portflio_mark,portflio_date
0,20160303,000001.SZ,10.11,0.9206,1.446607e+07,1.086248,H,B,B/H,201603
1,20160303,000004.SZ,29.86,30.3096,2.507544e+05,0.032993,L,S,S/L,201603
2,20160303,000006.SZ,9.38,2.8763,1.266295e+06,0.347669,M,B,B/M,201603
3,20160303,000008.SZ,8.33,4.4613,2.223143e+06,0.224150,M,B,B/M,201603
4,20160303,000009.SZ,12.25,4.3639,1.950332e+06,0.229153,M,B,B/M,201603
...,...,...,...,...,...,...,...,...,...,...
44707,20260303,603284.SH,47.70,1.7294,3.597286e+05,0.578235,H,S,S/H,202603
44708,20260303,688818.SH,59.28,19.7498,1.029648e+07,0.050633,L,B,B/L,202603
44709,20260303,688816.SH,67.00,3.8225,6.700000e+05,0.261609,M,S,S/M,202603
44710,20260303,920166.BJ,32.39,3.9907,2.438776e+05,0.250583,M,S,S/M,202603
44711,20260303,920168.BJ,24.98,2.3137,1.877832e+05,0.432208,M,S,S/M,202603

In [132]:
#将标记好的数据与股票数据合并merge()
data_rt = pd.DataFrame(data,columns=['trade_date','ts_code','close','total_mv']).rename(columns={'total_mv':'mkt'}).reset_index(drop=True)
data_rt['portflio_date'] = data_rt['trade_date'].apply(lambda x:x//10000*100+3 if (x//100%10>=3) or (x//1000%10==1) else (x//10000-1)*100+3)
data_rt

          trade_date    ts_code   close           mkt  portflio_date
0           20260327  000001.SZ   11.02  2.138532e+07         202603
1           20260326  000001.SZ   10.94  2.123007e+07         202603
2           20260325  000001.SZ   10.94  2.123007e+07         202603
3           20260324  000001.SZ   10.88  2.111364e+07         202603
4           20260323  000001.SZ   10.45  2.027918e+07         202603
...              ...        ...     ...           ...            ...
10081046    20260325  301682.SZ  128.65  1.563732e+06         202603
10081047    20260327  688781.SH   39.30  3.930000e+06         202603
10081048    20260326  688781.SH   40.79  4.079000e+06         202603
10081049    20260325  688781.SH   46.00  4.600000e+06         202603
10081050    20260327  920069.BJ   43.48  2.300701e+05         202603

[10081051 rows x 5 columns]

In [133]:
# data_rt = pd.merge(data_rt,data_5.drop(['trade_date','BM','mkt','pb','close'],axis=1),how='inner',left_on=['ts_code','portflio_date'],right_on=['ts_code','portflio_date'])
data_rt = pd.merge(data_rt,data_10.drop(['trade_date','BM','mkt','pb','close'],axis=1),how='inner',left_on=['ts_code','portflio_date'],right_on=['ts_code','portflio_date'])
data_rt

,trade_date,ts_code,close,mkt,portflio_date,group_BM,group_SIZE,portflio_mark
0,20260327,000001.SZ,11.02,2.138532e+07,202603,H,B,B/H
1,20260326,000001.SZ,10.94,2.123007e+07,202603,H,B,B/H
2,20260325,000001.SZ,10.94,2.123007e+07,202603,H,B,B/H
3,20260324,000001.SZ,10.88,2.111364e+07,202603,H,B,B/H
4,20260323,000001.SZ,10.45,2.027918e+07,202603,H,B,B/H
...,...,...,...,...,...,...,...,...
9530610,20260306,920168.BJ,24.24,1.822203e+05,202603,M,S,S/M
9530611,20260305,920168.BJ,25.50,1.916922e+05,202603,M,S,S/M
9530612,20260304,920168.BJ,24.58,1.847762e+05,202603,M,S,S/M
9530613,20260303,920168.BJ,24.98,1.877832e+05,202603,M,S,S/M
9530614,20260302,920168.BJ,26.02,1.956012e+05,202603,M,S,S/M

In [134]:
#股票的收益率序列
data_rt = data_rt.sort_values(by='trade_date',ascending=True)
data_rt['ret'] = data_rt.groupby('ts_code')['close'].pct_change()
data_rt = data_rt.dropna(subset=['ret'])
data_rt

,trade_date,ts_code,close,mkt,portflio_date,group_BM,group_SIZE,portflio_mark,ret
6128112,20160302,002753.SZ,34.03,3.358761e+05,201603,M,S,S/M,0.099871
3511575,20160302,002301.SZ,15.58,5.820688e+05,201603,L,S,S/L,0.056988
4777304,20160302,300218.SZ,11.38,2.469255e+05,201603,H,S,S/H,0.059590
266637,20160302,000534.SZ,9.55,4.696548e+05,201603,M,S,S/M,0.054084
3089687,20160302,002156.SZ,12.05,9.015533e+05,201603,H,B,B/H,0.059807
...,...,...,...,...,...,...,...,...,...
3309753,20260327,002229.SZ,18.09,8.976104e+05,202603,L,B,B/L,-0.007135
9110425,20260327,688325.SH,127.96,1.102235e+06,202603,L,B,B/L,-0.023728
3307339,20260327,002249.SZ,9.29,2.289114e+06,202603,M,B,B/M,0.003240
3680896,20260327,002340.SZ,8.12,4.143907e+06,202603,M,B,B/M,0.027848
0,20260327,000001.SZ,11.02,2.138532e+07,202603,H,B,B/H,0.007313

In [135]:
#20160302才进行建仓划分，故该日收益率ret为0
data_rt.loc[data_rt.trade_date==20160302,'ret']=0

#将每个月按照SIZE与BM分组，计算组内各支股票收益率市值加权综合收益率
port_ret = data_rt.groupby(['trade_date','portflio_mark']).apply(lambda x: (x['ret']*x['mkt']).sum()/x['mkt'].sum())
port_ret = port_ret.reset_index()  #重新设置索引
port_ret.rename(columns={port_ret.columns[-1]:'ret'},inplace=True)  #重新设置列名
port_ret=port_ret.pivot(index='trade_date',columns='portflio_mark',values='ret')  #将表格改为透视表
port_ret

/var/folders/ss/hq0_l7mj2f35ct8zlh27s1p80000gn/T/ipykernel_61384/424424300.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  port_ret = data_rt.groupby(['trade_date','portflio_mark']).apply(lambda x: (x['ret']*x['mkt']).sum()/x['mkt'].sum())

portflio_mark       B/H       B/L       B/M       S/H       S/L       S/M
trade_date
20160302       0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
20160303       0.003246 -0.002292  0.002391  0.004357  0.000404  0.003811
20160304       0.019727 -0.038702 -0.019304 -0.028790 -0.052677 -0.040832
20160307       0.003146  0.023724  0.019301  0.031248  0.030663  0.032934
20160308       0.001111  0.006046  0.000669  0.009909  0.014595  0.013947
...                 ...       ...       ...       ...       ...       ...
20260323      -0.031473 -0.043142 -0.029486 -0.056190 -0.052935 -0.055494
20260324       0.014519  0.022554  0.016183  0.041156  0.040251  0.041305
20260325       0.009189  0.021239  0.012272  0.021249  0.020299  0.020721
20260326      -0.005273 -0.016316 -0.012429 -0.010234 -0.018021 -0.015432
20260327       0.000839  0.013304  0.011926  0.015343  0.012928  0.016816

[2447 rows x 6 columns]

In [136]:
port_ret['SMB']=(port_ret['S/L']+port_ret['S/M']+port_ret['S/H'])/3-(port_ret['B/L']+port_ret['B/M']+port_ret['B/H'])/3

In [137]:
port_ret['HML']=(port_ret['S/H']+port_ret['B/H'])/2-(port_ret['S/L']+port_ret['B/L'])/2

In [138]:
ff3=port_ret.loc[:,['SMB','HML']].copy()
ff3=ff3.reset_index()
ff3.columns=['tradedate','SMB','HML']
ff3

      tradedate       SMB       HML
0      20160302  0.000000  0.000000
1      20160303  0.001742  0.004745
2      20160304 -0.028007  0.041159
3      20160307  0.016225 -0.009996
4      20160308  0.010209 -0.004811
...         ...       ...       ...
2442   20260323 -0.020173  0.004207
2443   20260324  0.023152 -0.003565
2444   20260325  0.006523 -0.005550
2445   20260326 -0.003223  0.009415
2446   20260327  0.006339 -0.005026

[2447 rows x 3 columns]

In [139]:
# index_daily
ff3['mkt_rf'] = index_daily['pct_chg'].copy().apply(lambda x:x/100)
#无风险利率rf=0.000041
ff3['rf'] = 0.000041
ff3

      tradedate       SMB       HML    mkt_rf        rf
0      20160302  0.000000  0.000000 -0.070206  0.000041
1      20160303  0.001742  0.004745  0.002800  0.000041
2      20160304 -0.028007  0.041159  0.017543  0.000041
3      20160307  0.016225 -0.009996 -0.069333  0.000041
4      20160308  0.010209 -0.004811  0.020392  0.000041
...         ...       ...       ...       ...       ...
2442   20260323 -0.020173  0.004207  0.000888  0.000041
2443   20260324  0.023152 -0.003565  0.000135  0.000041
2444   20260325  0.006523 -0.005550 -0.004491  0.000041
2445   20260326 -0.003223  0.009415  0.000950  0.000041
2446   20260327  0.006339 -0.005026 -0.000270  0.000041

[2447 rows x 5 columns]

In [159]:
ff3_ = ff3.copy()
ff3_ = ff3_.rename(columns={'tradedate':'ann_date'}).reset_index(drop=True)
ff3_

      ann_date       SMB       HML    mkt_rf        rf
0     20160302  0.000000  0.000000 -0.070206  0.000041
1     20160303  0.001742  0.004745  0.002800  0.000041
2     20160304 -0.028007  0.041159  0.017543  0.000041
3     20160307  0.016225 -0.009996 -0.069333  0.000041
4     20160308  0.010209 -0.004811  0.020392  0.000041
...        ...       ...       ...       ...       ...
2442  20260323 -0.020173  0.004207  0.000888  0.000041
2443  20260324  0.023152 -0.003565  0.000135  0.000041
2444  20260325  0.006523 -0.005550 -0.004491  0.000041
2445  20260326 -0.003223  0.009415  0.000950  0.000041
2446  20260327  0.006339 -0.005026 -0.000270  0.000041

[2447 rows x 5 columns]

In [161]:
ff3_['ann_date'] = pd.to_datetime(ff3_['ann_date'], format='%Y%m%d')
ff3_.set_index('ann_date', inplace=True)
ff3_

                 SMB       HML    mkt_rf        rf
ann_date
2016-03-02  0.000000  0.000000 -0.070206  0.000041
2016-03-03  0.001742  0.004745  0.002800  0.000041
2016-03-04 -0.028007  0.041159  0.017543  0.000041
2016-03-07  0.016225 -0.009996 -0.069333  0.000041
2016-03-08  0.010209 -0.004811  0.020392  0.000041
...              ...       ...       ...       ...
2026-03-23 -0.020173  0.004207  0.000888  0.000041
2026-03-24  0.023152 -0.003565  0.000135  0.000041
2026-03-25  0.006523 -0.005550 -0.004491  0.000041
2026-03-26 -0.003223  0.009415  0.000950  0.000041
2026-03-27  0.006339 -0.005026 -0.000270  0.000041

[2447 rows x 4 columns]

In [162]:
ff3_ = ff3_.loc[ff3_.index.get_level_values("ann_date") >= "2016-03-01"]
ff3_ = ff3_.resample('M').last()
ff3_ = ff3_.loc[ff3_.index.get_level_values("ann_date") >= "2016-04-01"]
ff3_

/var/folders/ss/hq0_l7mj2f35ct8zlh27s1p80000gn/T/ipykernel_61384/4056693361.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  ff3_ = ff3_.resample('M').last()

                 SMB       HML    mkt_rf        rf
ann_date
2016-04-30 -0.001156  0.000638  0.000912  0.000041
2016-05-31  0.001350 -0.011931 -0.014808  0.000041
2016-06-30  0.004969  0.007979 -0.026001  0.000041
2016-07-31 -0.001856  0.001856 -0.003304  0.000041
2016-08-31  0.000117  0.001372  0.003461  0.000041
...              ...       ...       ...       ...
2025-11-30  0.009435 -0.003411  0.004468  0.000041
2025-12-31  0.002131  0.004884  0.003474  0.000041
2026-01-31  0.010251 -0.000439  0.008118  0.000041
2026-02-28  0.006570  0.004153  0.003167  0.000041
2026-03-31  0.006339 -0.005026 -0.000270  0.000041

[120 rows x 4 columns]

In [163]:
ff3_.to_feather("ff3/ff3_factors.feather")